### ISSUE TITLE
Pyrmount depreciated? Test net advice or recommendations?

### ISSUE THREAD

**Issue by JordanDworaczyk** [SomerEsat/ethereum-staking-guides#3]
Hello, I'd just like to ask a question. I am looking for a guide for staking on the test net. I noticed that you have said that the Pyrmount guides have been depreciated. I was planning on using these guides to practice staking but now I am not sure. Do you have any advice or recommendations for a staking guide using a test net? I'd like to practice. Thanks!

P.S. I suppose that I am particularly referring to **Ubuntu/Lighthouse** guide's new note that was updated and committed [here](https://github.com/SomerEsat/ethereum-staking-guide/commit/d6d0aca2e75c895ae43e8d7d830aeb4b84b0bb03#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

**Comment by SomerEsat** [comment]
Hello Jordan,

I am working on updating the Ubuntu/Lighthouse guide to Prater this weekend. You can use the Nimbus guide as a reference for the "Prater" related settings. There is not a huge amount of difference. Or you can simply wait for me to publish the updated lighthouse guide, hopefully in the next few hours.

**Comment by JordanDworaczyk** [comment]
Ah, okay, I see. I think that I might take look at the other guides and see how they differ since you say there is not a huge amount of difference. I will take note that Prater is now the new long-term ETH2 test net. 

Thanks for the help and advice!
