### ISSUE TITLE
Prysm on Prater expected anytime soon?

### ISSUE THREAD

**Issue by pablote** [SomerEsat/ethereum-staking-guides#4]
Your guides are amazing, I was wondering if you were planning to do Prysm on Prater? I'm looking fwd to replace my Pyrmont client.

**Comment by SomerEsat** [comment]
Yes! I am working on it. Hopefully before the end of the year. Thanks for the kind words.


On Dec 21, 2021, at 11:44 AM, Pablo Compagni ***@***.***> wrote:

﻿
Your guides are amazing, I was wondering if you were planning to do Prysm on Prater? I'm looking fwd to replace my Pyrmont client.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
