### ISSUE TITLE
Besu needs --rpc-http-enabled flag

### ISSUE THREAD

**Issue by diglos** [SomerEsat/ethereum-staking-guides#5]
Hi,

We are running a Besu+Teku node and Teku doesn't communicate with Besu unless `--rpc-http-enabled `flag is added to the configuration (it notices that EL is online but they cannot talk to each other).

**Comment by SomerEsat** [comment]
Thanks for reaching out.

The `--rpc-http-enabled` flag should only be required if you are running a version of Besu with no TDD set (see: https://github.com/hyperledger/besu/pull/4190). However, given the TDD has been set in the latest version (see: https://github.com/hyperledger/besu/pull/4260), it no longer is required. 

Make sure you're running the latest version of Besu (22.7.1) and Teku (22.9.0) and using the authenticated endpoints to communicate (port 8551 with a config entry to the JWT in each client) and you shouldn't need that flag.

The combination has been explicitly tested on mainnet, as are all combinations/flags in my guides.

**Comment by diglos** [comment]
Hey :-), thanks for the quick response.

Let's see. Versions are correct:

```
teku --version
teku/v22.9.0/linux-aarch_64/-privatebuild-openjdk64bitservervm-java-11
besu --version
besu/v22.7.1/linux-aarch_64/openjdk-java-11
```
If I run these configs:

Besu: `--data-path=/home/ethereum/.besu --sync-mode=X_SNAP --data-storage-format=BONSAI --p2p-port=30328 --engine-jwt-secret=/etc/ethereum/jwtsecret --metrics-enabled`

Teku: `--network=mainnet --eth1-endpoint=http://localhost:8545 --p2p-port=9028 --data-path=/home/ethereum/.teku/ --ee-endpoint=http://127.0.0.1:8551 --ee-jwt-secret-file=/etc/ethereum/jwtsecret --validators-proposer-default-fee-recipient=0xd1933DF1c223ad7CB5716B066cA26BC24569e622 --metrics-enabled`

I repeateadly see the following  in Teku logs:

`Eth1 service down or still syncing for 4891s, retrying`

If I add the -`-rpc-http-enabled` flag to Besu it starts loading the Eth1 deposits and the `Eth1 service down or still syncing for 4891s, retrying` messages go away.

Do you see something missing in the configs without the flag?

**Comment by SomerEsat** [comment]
Yes - this is redundant and no longer required: `--eth1-endpoint=http://localhost:8545`. Having that line requires the `--rpc-http-enabled` flag. But - the merge utilizes the API engine which is via the authenticated 8551 port. Once you remove it, the issue will disappear, assuming Besu is fully synced.

**Comment by SomerEsat** [comment]
Note my config from my guide:

Besu:
```
ExecStart=/usr/local/bin/besu/bin/besu \
  --network=mainnet \
  --sync-mode=X_SNAP \
  --data-path=/var/lib/besu \
  --data-storage-format=BONSAI \
  --engine-jwt-secret=/var/lib/jwtsecret/jwt.hex
```

And Teku:
```
ExecStart=/usr/local/bin/teku/bin/teku \
  --network=mainnet \
  --data-path=/var/lib/teku \
  --validator-keys=/var/lib/teku/validator_keys:/var/lib/teku/validator_keys \
  --ee-endpoint=http://127.0.0.1:8551 \
  --ee-jwt-secret-file=/var/lib/jwtsecret/jwt.hex \
  --validators-proposer-default-fee-recipient=FeeRecipientAddress \
  --initial-state=CheckpointSyncURL \
  --validators-graffiti="<yourgraffiti>"
```

**Comment by diglos** [comment]
Ah, ok, it was Teku config. Thanks for the explanation.
