### ISSUE TITLE
Consider adding a timeout to the Geth systemd configurations

### ISSUE THREAD

**Issue by burz** [SomerEsat/ethereum-staking-guides#6]
Hey @SomerEsat, I have found your guides very helpful!

An issue I have run into with Geth is that the proposed systemd configuration file uses the default timeout when shutting down. Since Geth sometimes can take quite a while to write its state to disk, this can lead to bad shutdowns (as systemd simply kills Geth after the default timeout) that corrupt Geth's state. This can often take hours or days to fix (I have for example recently seen it have to go back in history and start redownloading the state from over 1 week and 4 days ago).

Therefore, I think it might be helpful to add the `TimeoutStopSec=600` variable in the Geth systemd configuration (i.e. a timeout of 10 minutes) so that Geth should almost certainly have enough time to write to disk before it is killed (as eluded to here for example: https://github.com/ethereum/go-ethereum/issues/24416).

Thanks again for all you do for the space!

**Comment by SomerEsat** [comment]
Hey @burz,

Added the timeout after consulting with a Geth dev ([here](https://discord.com/channels/482467812179181568/482467812816977921/1042685104008478720)) and verifying the config change doesn't break the existing service.

All guides have been updated.

Thanks for the suggestion!
