### ISSUE TITLE
Consider removing `=` in Lighthouse flag.

### ISSUE THREAD

**Issue by schmoelder** [SomerEsat/ethereum-staking-guides#8]
In your [lighthouse guide](https://someresat.medium.com/guide-to-staking-on-ethereum-ubuntu-lighthouse-773f5d982e03), you write the following when explaining the additional flags of the beacon node service:

> --execution-endpoint=http://127.0.0.1:8551 The address of the Execution Client. Should be the same for all Execution Clients detailed in this guide.

I was wondering, is the `=` correct here? In the main config file, you don't use it.

```
[Unit]
Description=Lighthouse Consensus Client BN (Mainnet)
Wants=network-online.target
After=network-online.target[Service]
User=lighthousebeacon
Group=lighthousebeacon
Type=simple
Restart=always
RestartSec=5
ExecStart=/usr/local/bin/lighthouse bn \
  --network mainnet \
  --datadir /var/lib/lighthouse \
  --http \
  --execution-endpoint http://127.0.0.1:8551 \
  --execution-jwt /var/lib/jwtsecret/jwt.hex \
  --checkpoint-sync-url CheckpointSyncURL[Install]
WantedBy=multi-user.target
```

**Comment by SomerEsat** [comment]
Great catch, thank you! 

I have updated both the mainnet and testnet guides to remove the '=' from the flags description section. The config is correct.

**Comment by Obinna26** [comment]
> In your [lighthouse guide](https://someresat.medium.com/guide-to-staking-on-ethereum-ubuntu-lighthouse-773f5d982e03), you write the following when explaining the additional flags of the beacon node service:
> 
> > --execution-endpoint=http://127.0.0.1:8551 The address of the Execution Client. Should be the same for all Execution Clients detailed in this guide.
> 
> I was wondering, is the `=` correct here? In the main config file, you don't use it.
> 
> ```
> [Unit]
> Description=Lighthouse Consensus Client BN (Mainnet)
> Wants=network-online.target
> After=network-online.target[Service]
> User=lighthousebeacon
> Group=lighthousebeacon
> Type=simple
> Restart=always
> RestartSec=5
> ExecStart=/usr/local/bin/lighthouse bn \
>   --network mainnet \
>   --datadir /var/lib/lighthouse \
>   --http \
>   --execution-endpoint http://127.0.0.1:8551 \
>   --execution-jwt /var/lib/jwtsecret/jwt.hex \
>   --checkpoint-sync-url CheckpointSyncURL[Install]
> WantedBy=multi-user.target
> ```
> 
> Great catch, thank you!

I have updated both the mainnet and testnet guides to remove the '=' from the flags description section. The config is correct.
